version: '3.8'

services:
  db:
    image: postgres:14
    container_name: container_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass1234
      POSTGRES_DB: task_api_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    container_name: container_api
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:pass1234@db:5432/task_api_db
      - DATABASE_HOST=db
    depends_on:
      - db

volumes:
  postgres_data:
